# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Weather' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Weather
    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
    pod 'SwiftyJSON', '~> 3.1'

  target 'WeatherTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Nimble', '~> 7.0'
    pod 'RxSwift', '~> 4.0'
    pod 'Quick', '~> 1.1'

  end

end

# enable bitcode on all the pods
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      cflags = config.build_settings['OTHER_CFLAGS'] || ['$(inherited)']
      cflags << '-fembed-bitcode'
      config.build_settings['OTHER_CFLAGS'] = cflags
    end
  end
end
